on:
  issue:
    types: [opened, closed]
  
jobs: 
  issue-ops:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/github-script@v3
      - run: gh issue comment ${{ github.event.issue.number }} --body "Hallo doe het chechk ff issue"