on:
  issues:
    types: [opened, closed]

jobs: 
  issue-ops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh issue comment ${{ github.event.issue.number }} --body "Hallo doe het chechk ff issue"
    env:
      GH_TOKEN: ${{ github.token }}
